[package]
name = "typestate-noise"
version = "0.1.0"
edition = "2021"

[dependencies]
x25519-dalek = { version = "2", features = ["reusable_secrets", "static_secrets","getrandom"] }
chacha20poly1305 = "0.10"
sha2 = "0.10"
bytes = "1"
hmac = "0.12"
